
try:
    #intentamos correr este codigo 
    #puede haber errores
    result = 10 + "10"
    print(result)
except:
    print("parece que hay un error, escribe bien la variable")